### ISSUE TITLE
Implement phase 2 support

### ISSUE THREAD

**Issue by kobigurk** [celo-org/snark-setup-coordinator#14]
Currently the code base supports the phase 1 flow. The phase 2 flow is similar but has some subtleties and different binaries. 

In terms of client behavior, besides adding support for the commands necessary for phase 2, this could be facilitated  by adding more fields to the ceremony state.

**Comment by kobigurk-clabs** [comment]
@mstraka100 to run end-to-end test and backtrack what's missing/wrong.
